# Pipeline auto assign current milestone for PR after the PR is merge
name: Assign Milestone
on:
  pull_request:
    types: [closed]

jobs:
  assign_milestone:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Assign Milestone
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { number, merged } = context.payload.pull_request;
            if (merged) {
              const { data: milestones } = await github.issues.listMilestones({
                owner,
                repo,
                state: 'open',
              });
              const currentMilestone = milestones.find((milestone) => milestone.title === 'Current');
              if (currentMilestone) {
                await github.issues.addLabels({
                  owner,
                  repo,
                  issue_number: number,
                  labels: [currentMilestone.title],
                });
              }
            }
