name: build-linux-x64
on:
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
        default: 'refs/heads/main'
      enable_condition:
        required: true
        type: boolean
        default: false
      upload_cloudflare_r2:
        required: true
        type: boolean
        default: false
      new_version:
        required: true
        type: string
        default: ''
    # secrets:
    #   CLOUDFLARE_R2_PUBLIC_URL:
    #     required: false
    #   CLOUDFLARE_R2_BUCKET_NAME:
    #     required: false
    #   CLOUDFLARE_R2_ACCESS_KEY_ID:
    #     required: false
    #   CLOUDFLARE_R2_SECRET_ACCESS_KEY:
    #     required: false
    #   CLOUDFLARE_ACCOUNT_ID:
    #     required: false
    #   CODE_SIGN_P12_BASE64:
    #     required: false
    #   CODE_SIGN_P12_PASSWORD:
    #     required: false
    #   APPLE_ID:
    #     required: false
    #   APPLE_APP_SPECIFIC_PASSWORD:
    #     required: false
    #   DEVELOPER_ID:
    #     required: false

jobs:
  build-macos:
    runs-on: macos-latest
    environment: production
    permissions:
      contents: write
    steps:
      - name: Getting the repo
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}

      - name: Installing node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.0.1


      - name: Update app version based on latest release tag with build number
        id: version_update
        run: |
          # Update the version in electron/package.json
          jq --arg version "${{ inputs.new_version }}" '.version = $version' electron/package.json > /tmp/package.json
          mv /tmp/package.json electron/package.json

          jq --arg version "${{ inputs.new_version }}" '.version = $version' web/package.json > /tmp/package.json
          mv /tmp/package.json web/package.json

          jq '.build.publish = [{"provider": "generic", "url": "${{ secrets.CLOUDFLARE_R2_PUBLIC_URL }}", "channel": "latest"}]' electron/package.json > /tmp/package.json
          mv /tmp/package.json electron/package.json

      - name: Get Cer for code signing
        run: base64 -d <<< "$CODE_SIGN_P12_BASE64" > /tmp/codesign.p12
        shell: bash
        env:
          CODE_SIGN_P12_BASE64: ${{ secrets.CODE_SIGN_P12_BASE64 }}

      - uses: apple-actions/import-codesign-certs@v2
        continue-on-error: true
        with:
          p12-file-base64: ${{ secrets.CODE_SIGN_P12_BASE64 }}
          p12-password: ${{ secrets.CODE_SIGN_P12_PASSWORD }}

      - name: Build and publish app
        run: |
          make build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_LINK: "/tmp/codesign.p12"
          CSC_KEY_PASSWORD: ${{ secrets.CODE_SIGN_P12_PASSWORD }}
          CSC_IDENTITY_AUTO_DISCOVERY: "true"
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APP_PATH: "."
          DEVELOPER_ID: ${{ secrets.DEVELOPER_ID }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: jan-mac-x64-${{ inputs.new_version }}
          path: ./electron/dist/jan-mac-x64-${{ inputs.new_version }}.dmg

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: jan-mac-arm64-${{ inputs.new_version }}
          path: ./electron/dist/jan-mac-arm64-${{ inputs.new_version }}.dmg

      - name: put-object using awscli s3api
        if: eq(${{ inputs.upload_cloudflare_r2 }}, true)
        continue-on-error: true
        run: |
          ls -al ./electron/dist
          aws s3api put-object --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com --bucket ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }} --key "latest/jan-mac-x64-${{ inputs.new_version }}.dmg" --body "./electron/dist/jan-mac-x64-${{ inputs.new_version }}.dmg" --content-type "application/octet-stream"
          aws s3api put-object --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com --bucket ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }} --key "latest/jan-mac-arm64-${{ inputs.new_version }}.dmg" --body "./electron/dist/jan-mac-arm64-${{ inputs.new_version }}.dmg" --content-type "application/octet-stream"
          aws s3api put-object --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com --bucket ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }} --key "latest/jan-mac-x64-${{ inputs.new_version }}.zip" --body "./electron/dist/jan-mac-x64-${{ inputs.new_version }}.zip" --content-type "application/zip"
          aws s3api put-object --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com --bucket ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }} --key "latest/jan-mac-arm64-${{ inputs.new_version }}.zip" --body "./electron/dist/jan-mac-arm64-${{ inputs.new_version }}.zip" --content-type "application/zip"
          aws s3api put-object --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com --bucket ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }} --key "${{ inputs.new_version }}/jan-mac-x64-${{ inputs.new_version }}.dmg" --body "./electron/dist/jan-mac-x64-${{ inputs.new_version }}.dmg" --content-type "application/octet-stream"
          aws s3api put-object --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com --bucket ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }} --key "${{ inputs.new_version }}/jan-mac-arm64-${{ inputs.new_version }}.dmg" --body "./electron/dist/jan-mac-arm64-${{ inputs.new_version }}.dmg" --content-type "application/octet-stream"
          aws s3api put-object --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com --bucket ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }} --key "${{ inputs.new_version }}/latest-mac.yml" --body "./electron/dist/latest-mac.yml" --content-type "text/yaml"
          aws s3api put-object --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com --bucket ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }} --key "latest/latest-mac.yml" --body "./electron/dist/latest-mac.yml" --content-type "text/yaml"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_EC2_METADATA_DISABLED: "true"

