name: build-windows-x64
on:
  workflow_call:
    secrets:
      CLOUDFLARE_R2_BUCKET_NAME:
        required: false
      CLOUDFLARE_R2_ACCESS_KEY_ID:
        required: false
      CLOUDFLARE_R2_SECRET_ACCESS_KEY:
        required: false
      CLOUDFLARE_ACCOUNT_ID:
        required: false

jobs:
  delete-cloudflare-r2-folder:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: install-aws-cli-action
        uses: unfor19/install-aws-cli-action@v1
      - name: Delete cloudflare-r2 folder using awscli s3api
        continue-on-error: true
        run: |
          # Get the list of objects in the 'latest' folder
          OBJECTS=$(aws s3api list-objects --bucket ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }} --prefix "latest/" --query 'Contents[].{Key: Key}' --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com | jq -c .)
          
          # Create a JSON file for the delete operation
          echo "{\"Objects\": $OBJECTS, \"Quiet\": false}" > delete.json
          
          # Delete the objects
          echo q | aws s3api delete-objects --bucket ${{ secrets.CLOUDFLARE_R2_BUCKET_NAME }} --delete file://delete.json --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
          
          # Remove the JSON file
          rm delete.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: auto
          AWS_EC2_METADATA_DISABLED: "true"

