name: Jan Build Electron Pre Release

on:
  push:
    branches:
      - main
    paths:
      - "!README.md"

jobs:
  delete-cloudflare-r2-folder:
    uses: ./.github/workflows/delete-cloudflare-r2-folder.yml

  # Job create Update app version based on latest release tag with build number and save to output
  get-update-version:
    uses: ./.github/workflows/get-update-version.yml

  build-macos:
    uses: ./.github/workflows/build-macos.yml
    needs: [delete-cloudflare-r2-folder, get-update-version]
    with:
      ref: refs/heads/main
      enable_condition: true
      upload_cloudflare_r2: true
      new_version: ${{ needs.get-update-version.outputs.new_version }}

  build-windows-x64:
    uses: ./.github/workflows/build-windows-x64.yml
    needs: [delete-cloudflare-r2-folder, get-update-version]
    with:
      ref: refs/heads/main
      enable_condition: true
      upload_cloudflare_r2: true
      new_version: ${{ needs.get-update-version.outputs.new_version }}

  build-linux-x64:
    uses: ./.github/workflows/build-linux-x64.yml
    needs: [delete-cloudflare-r2-folder, get-update-version]
    with:
      ref: refs/heads/main
      enable_condition: true
      upload_cloudflare_r2: true
      new_version: ${{ needs.get-update-version.outputs.new_version }}

  noti-discord-nightly-and-update-url-readme:
    needs: [build-macos, build-windows-x64, build-linux-x64, delete-cloudflare-r2-folder, get-update-version]
    if: github.event_name == 'push'
    uses: ./.github/workflows/noti-discord-and-update-url-readme.yml
    with:
      ref: refs/heads/main
      build_reason: Nightly
      push_to_branch: main
      new_version: ${{ needs.get-update-version.outputs.new_version }}
