name: Jan Build Electron App Manual

on:
  workflow_dispatch:
    inputs:
      public_provider:
        type: choice
        description: 'Public Provider'
        options:
          - none
          - cloudflare-r2
        default: none

jobs:
  get-update-version:
    uses: ./.github/workflows/template-get-update-version.yml

  build-macos:
    uses: ./.github/workflows/template-build-macos.yml
    needs: [get-update-version]
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      public_provider: ${{ github.event.inputs.public_provider }}
      new_version: ${{ needs.get-update-version.outputs.new_version }}

  build-windows-x64:
    uses: ./.github/workflows/template-build-windows-x64.yml
    needs: [get-update-version]
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      public_provider: ${{ github.event.inputs.public_provider }}
      new_version: ${{ needs.get-update-version.outputs.new_version }}

  build-linux-x64:
    uses: ./.github/workflows/template-build-linux-x64.yml
    needs: [get-update-version]
    secrets: inherit
    with:
      ref: ${{ github.ref }}
      public_provider: ${{ github.event.inputs.public_provider }}
      new_version: ${{ needs.get-update-version.outputs.new_version }}

  noti-discord-manual-and-update-url-readme:
    needs: [build-macos, build-windows-x64, build-linux-x64, get-update-version]
    secrets: inherit
    if: github.event_name == 'workflow_dispatch' && ${{ github.event.inputs.public_provider }} == 'cloudflare-r2'
    uses: ./.github/workflows/template-noti-discord-and-update-url-readme.yml
    with:
      ref: refs/heads/main
      build_reason: Manual
      push_to_branch: main
      new_version: ${{ needs.get-update-version.outputs.new_version }}