name: Jan Build Electron App Nightly

on:
  schedule:
    - cron: '0 20 * * 2,3,4' # At 8 PM UTC on Tuesday, Wednesday, and Thursday, which is 3 AM UTC+7

jobs:
  # Get condition to upload to cloudflare re
  # get-condition-to-upload-cloudflare-r2:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     condition: ${{ steps.get-condition-to-upload-cloudflare-r2.outputs.condition }}
  #   steps:
  #     - name: Get condition to upload to cloudflare re
  #       id: get-condition-to-upload-cloudflare-r2
  #       run: |
  #         if [ "${{ github.event_name }}" == "schedule" ]; then
  #           echo "::set-output name=condition::true"
  #         else
  #           echo "::set-output name=condition::false"
  #         fi

  delete-cloudflare-r2-folder:
    uses: ./.github/workflows/delete-cloudflare-r2-folder.yml
    secrets: inherit

  # Job create Update app version based on latest release tag with build number and save to output
  get-update-version:
    uses: ./.github/workflows/get-update-version.yml

  build-macos:
    uses: ./.github/workflows/build-macos.yml
    needs: [delete-cloudflare-r2-folder, get-update-version]
    secrets: inherit
    with:
      ref: refs/heads/dev
      enable_condition: true
      upload_cloudflare_r2: true
      new_version: ${{ needs.get-update-version.outputs.new_version }}

  build-windows-x64:
    uses: ./.github/workflows/build-windows-x64.yml
    secrets: inherit
    needs: [delete-cloudflare-r2-folder, get-update-version]
    with:
      ref: refs/heads/dev
      enable_condition: true
      upload_cloudflare_r2: true
      new_version: ${{ needs.get-update-version.outputs.new_version }}

          
  build-linux-x64:
    uses: ./.github/workflows/build-linux-x64.yml
    secrets: inherit
    needs: [delete-cloudflare-r2-folder, get-update-version]
    with:
      ref: refs/heads/dev
      enable_condition: true
      upload_cloudflare_r2: true
      new_version: ${{ needs.get-update-version.outputs.new_version }}

  noti-discord-nightly-and-update-url-readme:
    needs: [build-macos, build-windows-x64, build-linux-x64, delete-cloudflare-r2-folder, get-update-version]
    secrets: inherit
    if: github.event_name == 'schedule'
    uses: ./.github/workflows/noti-discord-and-update-url-readme.yml
    with:
      ref: refs/heads/dev
      build_reason: Nightly
      push_to_branch: main
      new_version: ${{ needs.get-update-version.outputs.new_version }}
