name: Linter & Test
on:
  push:
    branches:
      - main
    paths:
      - 'electron/**'
      - .github/workflows/linter-and-test.yml
      - 'web/**'
      - 'package.json'
      - 'node_modules/**'
      - 'yarn.lock'

  pull_request:
    branches:
      - main
    paths:
      - 'electron/**'
      - .github/workflows/linter-and-test.yml
      - 'web/**'
      - 'package.json'
      - 'node_modules/**'
      - 'yarn.lock'

jobs:
  test-on-macos:
    runs-on: [self-hosted, macOS, macos-desktop]
    steps:
      - name: Getting the repo
        uses: actions/checkout@v3

      - name: Installing node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Linter and test
        run: |
          yarn config set network-timeout 300000
          yarn install
          yarn lint
          yarn build:plugins
          yarn build
          yarn test
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: "false"

  test-on-windows:
    runs-on: [self-hosted, Windows, windows-desktop]
    steps:
      - name: Getting the repo
        uses: actions/checkout@v3

      - name: Installing node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Linter and test
        run: |
          yarn config set network-timeout 300000
          yarn install
          yarn lint
          yarn build:plugins
          yarn build:win32
          yarn test

  test-on-ubuntu:
    runs-on: [self-hosted, Linux, ubuntu-desktop]
    steps:
      - name: Getting the repo
        uses: actions/checkout@v3

      - name: Installing node
        uses: actions/setup-node@v1
        with:
          node-version: 20

      - name: Linter and test
        run: |
          w_output=$(w)
          export DISPLAY=$(echo "$w_output" | awk '$3 ~ /:[0-9]+/ {print $3}')
          echo -e "Display ID: $DISPLAY"
          yarn config set network-timeout 300000
          yarn install
          yarn lint
          yarn build:plugins
          yarn build:linux
          yarn test